// Command bench measures apply-only, decode+apply, and full-pipeline
// throughput plus end-to-end latency, and writes a Markdown report. Logging
// uses the discard sink and timestamp checks are disabled so terminal/pipe
// speed cannot masquerade as book throughput.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"runtime"
	"strings"
	"sync"
	"time"

	"orderbook/book"
	"orderbook/feed"
	"orderbook/internal/asynclog"
	"orderbook/internal/metrics"
	"orderbook/internal/ring"
	"orderbook/internal/strategy"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		csvPath  = flag.String("csv", "btc_orderbook_updates.csv", "input CSV path")
		exchange = flag.String("exchange", "binance", "exchange")
		symbol   = flag.String("symbol", "BTC/USDT", "symbol")
		iters    = flag.Int("iters", 50, "measured iterations")
		warmup   = flag.Int("warmup", 5, "warmup iterations")
		ringCap  = flag.Int("ring", 4096, "event ring capacity")
		logRing  = flag.Int("log-ring", 4096, "log ring capacity")
		spin     = flag.Int("spin", 128, "backpressure spin count")
		out      = flag.String("out", "", "report output path (empty = stdout)")
	)
	flag.Parse()

	data, err := os.ReadFile(*csvPath)
	if err != nil {
		return err
	}
	recs, err := decodeAll(data)
	if err != nil {
		return err
	}
	if len(recs) == 0 {
		return fmt.Errorf("no records decoded from %s", *csvPath)
	}

	applyRate := benchApplyOnly(recs, *exchange, *symbol, *iters, *warmup)
	daRate := benchDecodeApply(data, *exchange, *symbol, *iters, *warmup)
	pipe := benchPipeline(data, *exchange, *symbol, *iters, *ringCap, *logRing, *spin)

	var b strings.Builder
	fmt.Fprintf(&b, "# Benchmark Report\n\n")
	fmt.Fprintf(&b, "_Generated by `cmd/bench`. Logging sink = discard; timestamp-policy = off; crossed-policy = off. "+
		"Numbers are hardware-specific; no absolute thresholds are claimed._\n\n")
	fmt.Fprintf(&b, "## Environment\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| Go | %s |\n", runtime.Version())
	fmt.Fprintf(&b, "| OS/Arch | %s/%s |\n", runtime.GOOS, runtime.GOARCH)
	fmt.Fprintf(&b, "| NumCPU | %d |\n", runtime.NumCPU())
	fmt.Fprintf(&b, "| GOMAXPROCS | %d |\n", runtime.GOMAXPROCS(0))
	fmt.Fprintf(&b, "| Fixture | %s (%d records) |\n", *csvPath, len(recs))
	fmt.Fprintf(&b, "| Iterations | %d (warmup %d) |\n", *iters, *warmup)
	fmt.Fprintf(&b, "| Event/Log ring | %d / %d |\n\n", *ringCap, *logRing)

	fmt.Fprintf(&b, "## Throughput (updates/sec)\n\n")
	fmt.Fprintf(&b, "| Stage | Rate |\n|---|---|\n")
	fmt.Fprintf(&b, "| apply-only | %s |\n", humanRate(applyRate))
	fmt.Fprintf(&b, "| decode + apply | %s |\n", humanRate(daRate))
	fmt.Fprintf(&b, "| full pipeline (decode+apply+ring+strategy+discard-log) | %s |\n\n", humanRate(pipe.throughput))

	fmt.Fprintf(&b, "## Latency — full pipeline (%d samples)\n\n", pipe.ingress.Count())
	fmt.Fprintf(&b, "```\n%s\n%s\n```\n", pipe.ingress.Summary("ingress->strategy"), pipe.apply.Summary("apply->strategy"))

	report := b.String()
	if *out == "" {
		fmt.Print(report)
		return nil
	}
	if err := os.WriteFile(*out, []byte(report), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
	return nil
}

func decodeAll(data []byte) ([]feed.Record, error) {
	dec := feed.NewDecoder(bytes.NewReader(data))
	var recs []feed.Record
	for {
		r, err := dec.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		recs = append(recs, r)
	}
	return recs, nil
}

func applyAll(recs []feed.Record, ex, sym string) {
	bk := book.New(ex, sym, book.Config{CrossedPolicy: book.PolicyOff, LevelHint: 512})
	var zero time.Time
	for i := range recs {
		switch recs[i].Kind {
		case feed.KindSnapshot:
			bk.ApplySnapshot(recs[i].Snapshot, zero)
		case feed.KindIncremental:
			bk.ApplyIncremental(recs[i].Incremental, zero)
		}
	}
}

func benchApplyOnly(recs []feed.Record, ex, sym string, iters, warmup int) float64 {
	for i := 0; i < warmup; i++ {
		applyAll(recs, ex, sym)
	}
	start := time.Now()
	for i := 0; i < iters; i++ {
		applyAll(recs, ex, sym)
	}
	d := time.Since(start)
	return metrics.Rate(uint64(iters*len(recs)), d)
}

func benchDecodeApply(data []byte, ex, sym string, iters, warmup int) float64 {
	run := func() int {
		dec := feed.NewDecoder(bytes.NewReader(data))
		bk := book.New(ex, sym, book.Config{CrossedPolicy: book.PolicyOff, LevelHint: 512})
		var zero time.Time
		n := 0
		for {
			r, err := dec.Next()
			if err == io.EOF {
				break
			}
			if err != nil {
				return n
			}
			switch r.Kind {
			case feed.KindSnapshot:
				bk.ApplySnapshot(r.Snapshot, zero)
			case feed.KindIncremental:
				bk.ApplyIncremental(r.Incremental, zero)
			}
			n++
		}
		return n
	}
	for i := 0; i < warmup; i++ {
		run()
	}
	start := time.Now()
	total := 0
	for i := 0; i < iters; i++ {
		total += run()
	}
	return metrics.Rate(uint64(total), time.Since(start))
}

type pipeResult struct {
	throughput float64
	ingress    *metrics.Histogram
	apply      *metrics.Histogram
}

func benchPipeline(data []byte, ex, sym string, iters, ringCap, logRing, spin int) pipeResult {
	lat := &strategy.Latency{IngressToRecv: metrics.NewHistogram(), ApplyToRecv: metrics.NewHistogram()}
	ctx := context.Background()
	var total uint64
	start := time.Now()
	for it := 0; it < iters; it++ {
		dec := feed.NewDecoder(bytes.NewReader(data))
		bk := book.New(ex, sym, book.Config{CrossedPolicy: book.PolicyOff, LevelHint: 512})
		lg, err := asynclog.New(asynclog.Config{Sink: asynclog.SinkDiscard, RingCapacity: logRing, Spin: spin})
		if err != nil {
			continue
		}
		events := ring.New[book.BookEvent](ringCap)
		var wg sync.WaitGroup
		wg.Add(2)
		go func() { defer wg.Done(); lg.Run(ctx) }()
		go func() { defer wg.Done(); strategy.Run(ctx, events, lg, strategy.BBO{}, lat, spin) }()
		pub := feed.SinkFunc(func(e book.BookEvent) error { return events.Push(ctx, e, spin) })
		st, _ := feed.Replay(ctx, dec, bk, pub,
			feed.Config{Mode: feed.Fast, Sync: &feed.TimestampPolicy{Mode: book.PolicyOff}}, feed.RealClock{})
		events.Close()
		wg.Wait()
		total += st.Accepted
	}
	return pipeResult{throughput: metrics.Rate(total, time.Since(start)), ingress: lat.IngressToRecv, apply: lat.ApplyToRecv}
}

func humanRate(r float64) string {
	switch {
	case r >= 1e6:
		return fmt.Sprintf("%.2fM", r/1e6)
	case r >= 1e3:
		return fmt.Sprintf("%.1fk", r/1e3)
	default:
		return fmt.Sprintf("%.0f", r)
	}
}
