package main

import (
	"crypto/sha256"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"
	"unsafe"

	"orderbook/internal/logx"
	"orderbook/internal/pipeline"
)

func renderReport(c config, fixture []byte, s suite) string {
	hash := sha256.Sum256(fixture)
	var b strings.Builder
	b.WriteString("# Benchmark Report\n\n")
	b.WriteString("> Generated by `cmd/bench` from the workloads in `docs/SPEC.md`. Results are hardware-specific. Measured pipelines use lossless delivery and the discard logger sink.\n\n")
	b.WriteString("## Environment and configuration\n\n| Field | Value |\n|---|---|\n")
	model := c.cpuModel
	if model == "" {
		model = discoverCPUModel()
	}
	fmt.Fprintf(&b, "| Run time | %s |\n| CPU | %s (%d logical CPUs) |\n| OS / architecture | %s / %s |\n| Go | %s |\n", time.Now().UTC().Format(time.RFC3339), model, runtime.NumCPU(), runtime.GOOS, runtime.GOARCH, runtime.Version())
	fmt.Fprintf(&b, "| GOMAXPROCS | %d |\n| GOGC / GOMEMLIMIT | %s / %s |\n", runtime.GOMAXPROCS(0), envOr("GOGC", "100 (default)"), envOr("GOMEMLIMIT", "off (default)"))
	fmt.Fprintf(&b, "| Fixture | `%s`; %d rows; SHA-256 `%x` |\n| Fixture sync | timestamp-step=100 source units; unit=ms |\n", c.csvPath, s.fixtureRows, hash)
	fmt.Fprintf(&b, "| Synthetic | seed=%d; positions=%d; max levels/side=%d; mix=35%% existing, 20%% delete, 25%% new, 20%% best-touch |\n", c.seed, c.synthetic, c.syntheticMax)
	fmt.Fprintf(&b, "| Rings | event=%d; log=%d; spin=%d |\n| Record sizes | pipeline.Event=%d B; logx.Record=%d B |\n| Logger | discard; lossless; zero drops required |\n| Fixture repetitions | %d measured after %d warmups |\n\n", c.eventRing, c.logRing, c.spin, unsafe.Sizeof(pipeline.Event{}), unsafe.Sizeof(logx.Record{}), c.fixtureIters, c.warmup)

	b.WriteString("## Throughput\n\nThe fixture is a correctness and representative-latency workload. W6a is the synthetic headline. W6 emits one record at a time and never retains the high-volume stream.\n\n")
	b.WriteString("| Workload | Events | Duration | Updates/s | Runtime allocs/op¹ | Runtime B/op¹ |\n|---|---:|---:|---:|---:|---:|\n")
	for _, m := range []measurement{s.apply, s.decodeApply, s.fixture, s.synthetic, s.snapshots} {
		row(&b, m)
	}
	b.WriteString("\n¹ Process-wide `runtime.MemStats` deltas are supporting end-to-end indicators. `go test -bench . -benchmem` is authoritative for microbenchmark allocation counts.\n\n")

	b.WriteString("## W8 synchronization-policy cost\n\nIdentical seeded streams carry timestamp steps and contiguous update-ID ranges.\n\n| Policy | Events | Updates/s |\n|---|---:|---:|\n")
	for _, m := range []measurement{s.policyStep, s.policyOff, s.policyID} {
		fmt.Fprintf(&b, "| %s | %d | %s |\n", m.name, m.n, rate(m.rate()))
	}

	b.WriteString("\n## Callback latency\n\n`IngressNS -> receiveNS` is primary. All endpoints share one local monotonic clock; historical CSV epochs are never subtracted from process time.\n\n```text\n")
	fmt.Fprintln(&b, s.fixture.ingress.Line("W1 ingress->callback"))
	fmt.Fprintln(&b, s.fixture.apply.Line("W1 apply->callback"))
	fmt.Fprintln(&b, s.synthetic.ingress.Line("W6a ingress->callback"))
	fmt.Fprintln(&b, s.synthetic.apply.Line("W6a apply->callback"))
	fmt.Fprintln(&b, s.synthetic.mutation.Line("W6a apply duration"))
	b.WriteString("```\n\n")

	fmt.Fprintf(&b, "## W7 paced replay diagnostics\n\nOne fixture pass at %.0fx, with source offsets rebased onto the local monotonic timeline.\n\n```text\n", c.pacedSpeed)
	fmt.Fprintln(&b, s.paced.due.Line("due->callback"))
	fmt.Fprintln(&b, s.paced.lateness.Line("scheduler lateness"))
	fmt.Fprintln(&b, s.paced.ingress.Line("ingress->callback"))
	b.WriteString("```\n\n")

	b.WriteString("## Queueing and backpressure\n\n")
	fmt.Fprintf(&b, "- W5 delivered %d/%d FIFO events with zero loss; delayed consumption caused %d producer waits; peak depth %d/%d.\n", s.backpressure.n, s.backpressure.n, s.backpressure.waits, s.backpressure.maxDepth, min(c.eventRing, 256))
	fmt.Fprintf(&b, "- W1 sampled event peak %d/%d; discard-log peak %d/%d; logger waits %d; drops %d.\n", s.fixture.eventDepth, c.eventRing, s.fixture.log.MaxDepth, c.logRing, s.fixture.log.WaitCount, s.fixture.log.Dropped)
	fmt.Fprintf(&b, "- W6a sampled event peak %d/%d; log peak %d/%d; logger waits %d; drops %d.\n", s.synthetic.eventDepth, c.eventRing, s.synthetic.log.MaxDepth, c.logRing, s.synthetic.log.WaitCount, s.synthetic.log.Dropped)
	fmt.Fprintf(&b, "- W6b sampled event peak %d/%d; log peak %d/%d; logger waits %d; drops %d.\n\n", s.snapshots.eventDepth, c.eventRing, s.snapshots.log.MaxDepth, c.logRing, s.snapshots.log.WaitCount, s.snapshots.log.Dropped)

	b.WriteString("## Reproduce\n\n```sh\ngo test -bench . -benchmem -run '^$' ./...\ngo run ./cmd/bench -csv btc_orderbook_updates.csv -synthetic 10000000 -out BENCHMARK.md\n```\n\nRun multiple times after warmup when comparing changes. Paced latency is a scheduler diagnostic, not a fast-throughput metric.\n")
	return b.String()
}

func row(b *strings.Builder, m measurement) {
	fmt.Fprintf(b, "| %s | %d | %s | %s | %.4f | %.2f |\n", m.name, m.n, m.duration.Round(time.Microsecond), rate(m.rate()), m.allocsPerOp(), m.bytesPerOp())
}
func rate(v float64) string {
	if v >= 1e6 {
		return fmt.Sprintf("%.2fM", v/1e6)
	}
	if v >= 1e3 {
		return fmt.Sprintf("%.1fk", v/1e3)
	}
	return fmt.Sprintf("%.0f", v)
}
func envOr(k, d string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return d
}
func discoverCPUModel() string {
	if runtime.GOOS == "darwin" {
		if out, e := exec.Command("sysctl", "-n", "machdep.cpu.brand_string").Output(); e == nil && strings.TrimSpace(string(out)) != "" {
			return strings.TrimSpace(string(out))
		}
	}
	if data, e := os.ReadFile("/proc/cpuinfo"); e == nil {
		for _, line := range strings.Split(string(data), "\n") {
			k, v, ok := strings.Cut(line, ":")
			if ok && strings.TrimSpace(k) == "model name" {
				return strings.TrimSpace(v)
			}
		}
	}
	return "unavailable (use -cpu-model to supply it)"
}
